[package]
name = "globed-shared"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.190", features = ["serde_derive"] }
serde_json = "1.0.108"
