[package]
name = "globed-shared"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp = { path = "../esp" }
globed-derive = { path = "../derive" }

anyhow = "1.0.75"
base64 = "0.21.5"
colored = "2.1.0"
crypto_box = { version = "0.9.1", features = ["std", "chacha20"] }
hmac = "0.12.1"
log = { version = "0.4.20" }
nohash-hasher = "0.2.0"
parking_lot = "0.12.1"
rand = "0.8.5"
reqwest = { version = "0.11.22", default-features = false, features = [
    "rustls-tls",
] }
sha2 = "0.10.8"
time = { version = "0.3.30", features = ["formatting"] }
