[package]
name = "observer"
version = "0.1.0"
edition = "2024"

[dependencies]
globed-shared = { path = "../shared" }
globed-derive = { path = "../derive" }
observer-shared = { path = "../observer-shared" }
esp = { path = "../esp" }

egui = "0.31.1"
