[package]
name = "llgvis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp = { path = "../server/esp" }
globed-derive = { path = "../server/derive" }
plotters = "0.3.5"
