name: Build Globed

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/*.md'
      - 'previews/**'
      - 'README.md'
      - 'rescale.py'

  # pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            build-config: RelWithDebInfo

          - name: macOS
            os: macos-latest

          - name: iOS
            os: macos-latest
            target: iOS

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # sdk: 'latest'
          sdk: 'nightly'
          build-config: ${{ matrix.config.build-config || 'Release' }}
          configure-args: '-DGLOBED_RELEASE=ON'
          export-pdb: true
          export-symbols: true
          combine: true
          target: ${{ matrix.config.target }}
          # sccache is broken on macos, so use no cache there :(
          ccache-variant: ${{ matrix.config.os != 'macos-latest' && 'sccache' || '' }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: globed-build-output
          path: ${{ steps.build.outputs.build-output }}

  release:
    name: Create nightly release
    runs-on: ubuntu-latest
    needs: package
    permissions: write-all

    steps:
      - uses: actions/download-artifact@v6
        with:
          path: './artifacts/'

      - uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Development Release'
          prerelease: true
          body: |
            This is a nightly release for commit ${{ github.sha }}. It may be unstable and contain bugs, so use at your own risk.
          files: |
            ./artifacts/globed-build-output/*.geode
            ./artifacts/globed-build-output/*.pdb
            ./artifacts/globed-build-output/*.sym